### ISSUE TITLE
Running Discord RPC on Synology DSM7.2 through Container Manager (Docker)

### ISSUE THREAD

**Issue by FloydianSound** [phin05/discord-rich-presence-plex#76] opened 2024-01-14 06:28 UTC
ss explained in the Title....

is it possible to run this in a Docker Container on a Synology Nas ?

**my specific setup :**
Synology DS224+ (DSM7.2)
Plex Media Server Package from official synology repo
running Tautulli and other plug-ins as Docker Containers (everything works find so far...)

i would like to run this script as a resident agent as well, so it would still update whatever app/media/location i access _(Plex/Plex HTPC/PlexAMP on Windows and Android)_

will i need to run a discord instance on the same or a different connected container ?
i don't have much experience with dockers, i'm still learning :)

Thanks !

**Comment by FloydianSound** [comment] 2024-01-23 09:54
thanks for you answer!

would a silent instance to push the right calls would work ?
like maybe having a browser session running in the background process, or something akin to that.
or maybe a plex integration ?

i'd really like to have this installed server-side and have all my webhooks and stuff be centralized this way, unless you have another idea in mind that could do something similar ?

**Comment by N72826** [comment] 2024-01-31 07:09
Wow I'm in the same boat, didn't think anyone else would ask about this. Currently, I have the script running at startup on my host system running windows but I would love to be able to run this containerized on my synology so I don't ever have to think about it. oh well.

**Comment by phin05** [comment] 2024-01-31 07:40
You'll have to run Discord on the NAS, and this can be done in a container as well.

Try this:
Run [kasmweb/discord](https://hub.docker.com/r/kasmweb/discord) with `/tmp/discord` from the host mounted into the container at `/tmp`. Access it through your browser as per their instructions and sign into Discord.
Run [ghcr.io/phin05/discord-rich-presence-plex](https://github.com/phin05/discord-rich-presence-plex/pkgs/container/discord-rich-presence-plex) with `/tmp/discord` from the host mounted into the container at `/run/app`.

**Comment by N72826** [comment] 2024-01-31 07:45
when you say:
>Run [kasmweb/discord](https://hub.docker.com/r/kasmweb/discord) with /tmp/discord from the host mounted into the container at /tmp.
You are saying mount the temp folder created by discord on my windows machine into the container at /tmp? Is that possible?

**Comment by phin05** [comment] 2024-01-31 07:50
> You are saying mount the temp folder created by discord on my windows machine into the container at /tmp? Is that possible?

No, `/tmp/discord` would be a new temporary folder on your NAS used by both kasmweb/discord and discord-rich-presence-plex. That needs to be mounted into the kasmweb/discord container as `/tmp` because that's where Discord running inside that container would store it's IPC Unix socket, and the discord-rich-presence-plex container looks for that socket in `/run/app` if exists so the same `/tmp/discord` host folder needs to be mounted into discord-rich-presence-plex as `/run/app`.

**Comment by N72826** [comment] 2024-01-31 07:50
I see. I will attempt this. That makes a lot more sense.

**Comment by N72826** [comment] 2024-01-31 08:10
this is the same issue I ran into last time. the kasmweb discord container fails to run for some reason. below I have provided an excerpt of the end of the log when attempting to launch the discord container for the first time.
```LaunchProcess: failed to execvp:
xdg-open
mainScreen.UpdaterEvents: UPDATER_HISTORY_QUERY_AND_TRUNCATE

** (xiccd:432): CRITICAL **: 08:09:18.476: Failed to connect to colord: Could not connect: No such file or directory

(nm-applet:425): nm-applet-WARNING **: 08:09:18.560: Error connecting to system D-Bus: Could not connect: No such file or directory

(nm-applet:425): nm-applet-WARNING **: 08:09:18.561: Could not connect: No such file or directory

(nm-applet:425): libnm-CRITICAL **: 08:09:18.562: ((libnm/nm-client.c:3905)): assertion '<dropped>' failed

(nm-applet:425): libnm-CRITICAL **: 08:09:18.564: ((libnm/nm-client.c:3859)): assertion '<dropped>' failed

(nm-applet:425): libnm-CRITICAL **: 08:09:18.564: ((libnm/nm-client.c:3937)): assertion '<dropped>' failed

(nm-applet:425): libnm-CRITICAL **: 08:09:18.564: ((libnm/nm-client.c:3986)): assertion '<dropped>' failed

(nm-applet:425): libnm-CRITICAL **: 08:09:18.564: ((libnm/nm-client.c:4026)): assertion '<dropped>' failed

(nm-applet:425): libnm-CRITICAL **: 08:09:18.564: ((libnm/nm-client.c:4042)): assertion '<dropped>' failed

(nm-applet:425): libnm-CRITICAL **: 08:09:18.564: ((libnm/nm-client.c:4080)): assertion '<dropped>' failed

(nm-applet:425): libnm-CRITICAL **: 08:09:18.564: ((libnm/nm-client.c:4598)): assertion '<dropped>' failed

(nm-applet:425): libnm-CRITICAL **: 08:09:18.564: ((libnm/nm-client.c:4598)): assertion '<dropped>' failed
system-config-printer-applet: failed to connect to system D-Bus```

**Comment by phin05** [comment] 2024-01-31 08:55
Is the container stopping after that? If not, did you try accessing it regardless of the error?

**Comment by N72826** [comment] 2024-01-31 08:56
Yes. I cannot connect to it. I will send the logs when trying in a second.

**Comment by N72826** [comment] 2024-01-31 08:58
```2024-01-31 08:57:53,139 [INFO] websocket 0: got client connection from 172.17.0.1
 2024-01-31 08:57:53,140 [DEBUG] websocket 0: non-SSL connection disallowed
 2024-01-31 08:57:53,140 [DEBUG] websocket 0: No connection after handshake
 2024-01-31 08:57:53,140 [DEBUG] websocket 0: handler exit
 2024-01-31 08:57:53,142 [INFO] websocket 1: got client connection from 172.17.0.1
 2024-01-31 08:57:53,143 [DEBUG] websocket 1: non-SSL connection disallowed
 2024-01-31 08:57:53,143 [DEBUG] websocket 1: No connection after handshake
 2024-01-31 08:57:53,143 [DEBUG] websocket 1: handler exit
 2024-01-31 08:57:53,144 [INFO] websocket 2: got client connection from 172.17.0.1
 2024-01-31 08:57:53,145 [DEBUG] websocket 2: non-SSL connection disallowed
 2024-01-31 08:57:53,145 [DEBUG] websocket 2: No connection after handshake
 2024-01-31 08:57:53,145 [DEBUG] websocket 2: handler exit
 2024-01-31 08:57:53,146 [INFO] websocket 3: got client connection from 172.17.0.1
 2024-01-31 08:57:53,147 [DEBUG] websocket 3: non-SSL connection disallowed
 2024-01-31 08:57:53,147 [DEBUG] websocket 3: No connection after handshake
 2024-01-31 08:57:53,147 [DEBUG] websocket 3: handler exit
 2024-01-31 08:57:53,153 [INFO] websocket 4: got client connection from 172.17.0.1
 2024-01-31 08:57:53,154 [DEBUG] websocket 4: non-SSL connection disallowed
 2024-01-31 08:57:53,154 [DEBUG] websocket 4: No connection after handshake
 2024-01-31 08:57:53,154 [DEBUG] websocket 4: handler exit
 2024-01-31 08:57:53,156 [INFO] websocket 5: got client connection from 172.17.0.1
 2024-01-31 08:57:53,157 [DEBUG] websocket 5: non-SSL connection disallowed
 2024-01-31 08:57:53,157 [DEBUG] websocket 5: No connection after handshake
 2024-01-31 08:57:53,157 [DEBUG] websocket 5: handler exit
 2024-01-31 08:57:53,158 [INFO] websocket 6: got client connection from 172.17.0.1
 2024-01-31 08:57:53,159 [DEBUG] websocket 6: non-SSL connection disallowed
 2024-01-31 08:57:53,159 [DEBUG] websocket 6: No connection after handshake
 2024-01-31 08:57:53,159 [DEBUG] websocket 6: handler exit
 2024-01-31 08:57:53,161 [INFO] websocket 7: got client connection from 172.17.0.1
 2024-01-31 08:57:53,161 [DEBUG] websocket 7: non-SSL connection disallowed
 2024-01-31 08:57:53,161 [DEBUG] websocket 7: No connection after handshake
 2024-01-31 08:57:53,161 [DEBUG] websocket 7: handler exit
 2024-01-31 08:57:53,162 [INFO] websocket 8: got client connection from 172.17.0.1
 2024-01-31 08:57:53,164 [DEBUG] websocket 8: non-SSL connection disallowed
 2024-01-31 08:57:53,164 [DEBUG] websocket 8: No connection after handshake
 2024-01-31 08:57:53,164 [DEBUG] websocket 8: handler exit
 2024-01-31 08:57:53,166 [INFO] websocket 9: got client connection from 172.17.0.1
 2024-01-31 08:57:53,167 [DEBUG] websocket 9: non-SSL connection disallowed
 2024-01-31 08:57:53,167 [DEBUG] websocket 9: No connection after handshake
 2024-01-31 08:57:53,167 [DEBUG] websocket 9: handler exit

**Comment by phin05** [comment] 2024-01-31 09:03
kasmweb/discord doesn't allow non-SSL HTTP connections. Change your URL's scheme to `https` and ignore the SSL errors shown by your browser.

**Comment by phin05** [comment] 2024-01-31 09:09
Haha, it's okay. Let me know if you manage to get it to work.

**Comment by phin05** [comment] 2024-01-31 09:25
Note for others who may be following the instructions in this thread: Create `/tmp/discord` manually with permissions set to 777 (`mkdir -m 777 /tmp/discord`) before running the containers to avoid certain other errors.

**Comment by phin05** [comment] 2024-01-31 10:01
@N72826 I ran into errors when I was testing this because the permissions on `/tmp/discord` were restrictive for non-root users due to it being automatically created by the Docker daemon which runs as root. Mounting that into the container as `/tmp` is problematic because `/tmp` needs to be accessible by every user. Not sure how you got around this but I had to manually set the permissions on `/tmp/discord` to 777 to get kasmweb/discord to run. I also realised that `/tmp` is not persistent, so if the system is rebooted, the same issue would occur since `/tmp/discord` wouldn't exist and the Docker daemon would auto-create it with restrictive permissions. To avoid this, I would suggest using a different persistent host directory, for example `/var/discord-tmp`, instead of `/tmp/discord`.

**Comment by N72826** [comment] 2024-01-31 10:07
well I have a synology share dedicated to persistent directories used by docker. A separate docker user is created upon the installation of docker and I gave that user full access to the specific share I use for those persistent directories. I think that is why I didn't run into any issues originally. For example, I have kasmweb-discord/tmp binded to /tmp within the discord container and that worked fine.

Now after setting up the compose stack in portainer, I can access the kasm container but something is preventing discord from being installed into kasm. I'm checking the logs real quick to see what the issue is.

**Comment by N72826** [comment] 2024-01-31 10:18
Not sure how this is possible, was able to get the discord container running using the run command. All I did was adapt the run command into a compose file. The only thing that cannot be adapted from the provided command is -it, which specifies the container as being interactive, launching you directly into the container as opposed to it running in the background.

**Comment by phin05** [comment] 2024-01-31 10:27
Can you verify that the permissions on `kasmweb-discord/tmp` is set to 777 (or 1777)? Run `stat /REDACTED/REDACTED/kasmweb-discord/tmp` and check the "Access" part.

**Comment by N72826** [comment] 2024-01-31 10:28
oh shit well its not.

**Comment by phin05** [comment] 2024-01-31 10:30
Oops, I mean `chmod`

**Comment by N72826** [comment] 2024-01-31 10:30
I knew it was one of them lol

**Comment by N72826** [comment] 2024-01-31 10:32
oh wait I'm tripping. it was 0777 from the beginning. I was looking at the wrong part.

**Comment by N72826** [comment] 2024-01-31 10:33
so now I'm confused. one sec let me try to run the container again and see where its failing.

**Comment by phin05** [comment] 2024-01-31 11:33
I'm not sure what's wrong. kasmweb/discord works for me with the same compose stack as yours.

However, while testing, I noticed that a couple more changes are required to make this work properly:

Firstly, setting `XDG_RUNTIME_DIR` for the kasmweb/discord container to `/run/user/1000` makes Discord use that directory instead of `/tmp` to store its IPC Unix socket file. With this, you can avoid mounting into `/tmp` and filling up the mounted host directory with other temporary junk.

Secondly, you need to set the `DRPP_CONTAINER_DEMOTION_UID_GID` environment variable for the discord-rich-presence-plex container to 1000. By default, my script demotes itself from root to user ID 10000, which prevents it from accessing the IPC Unix socket created by Docker in kasmweb/discord which is running as user ID 1000. So, this environment variable needs to be overridden to make my script demote itself to user ID 1000 instead.

My working compose stack is as under:
```yaml
services:
  kasmweb-discord:
    container_name: kasmweb-discord
    image: kasmweb/discord:1.14.0-rolling
    restart: unless-stopped
    ports:
      - 6901:6901
    shm_size: 512m
    environment:
      VNC_PW: password
      XDG_RUNTIME_DIR: /run/app
    volumes:
      - /var/discord-tmp:/run/app
  drpp:
    container_name: drpp
    image: ghcr.io/phin05/discord-rich-presence-plex:latest
    restart: unless-stopped
    environment:
      DRPP_CONTAINER_DEMOTION_UID_GID: 1000
    volumes:
      - /var/discord-tmp:/run/app:ro
      - ./drpp:/app/data
```

**Comment by N72826** [comment] 2024-01-31 11:56
dude! perfect timing. I made major progress after fucking around with it. I knew something was off when I could run the discord container manually through ssh but when trying to use portainer, it kept failing. Remember when I said this:
>well I have a synology share dedicated to persistent directories used by docker. A separate docker group* is created upon the installation of docker and I gave that docker group* full perms to the specific share I use for those persistent directories.

Well guess what, I took a shot in the dark and checked the docker group permissions through DSM and... the docker group never had perms. 

I gave it perms and now I am able to run the discord container and access it without problems. I was just about to get back to you about the socket permission issue so thank you. I will check out your suggestion, I believe it will work.

**Comment by N72826** [comment] 2024-01-31 13:32
Everything is working smoothly now and I couldn't be happier. Thanks man, I really appreciate your help. my discord is n72826 if you want to chat sometime.

**Comment by phin05** [comment] 2024-01-31 16:07
No problem, glad it works.

I've pushed a new version (v2.4.4) to address the permission issue. The `DRPP_CONTAINER_DEMOTION_UID_GID` environment variable is no longer required. Take a look at the "[Example using kasmweb/discord](https://github.com/phin05/discord-rich-presence-plex?tab=readme-ov-file#example-using-kasmwebdiscord)" section of the README for the updated compose stack which also includes a custom entry point for the kasmweb/discord container to fix initial permissions.

**Comment by phin05** [comment] 2024-02-01 07:50
@FloydianSound The [kasmweb/discord example](https://github.com/phin05/discord-rich-presence-plex?tab=readme-ov-file#docker-compose-example-using-kasmwebdiscord) added to the README is proven to work so I'll be closing this issue. Try it out and comment here if you need any assistance.

**Closed by phin05** 2024-02-01 07:50 UTC
Labels: question/problem

**Comment by FloydianSound** [comment] 2024-02-29 03:09
> @FloydianSound The [kasmweb/discord example](https://github.com/phin05/discord-rich-presence-plex?tab=readme-ov-file#docker-compose-example-using-kasmwebdiscord) added to the README is proven to work so I'll be closing this issue. Try it out and comment here if you need any assistance.

why thanks so much! 
i've had my hands busy this last month with work and i didn't follow up, here i am now !

this is great, i will go through the thread to read about it, and will get back to you to confirm it works on my end as well !

@N72826 glad we had this same question and need ! 🦾 
@phin05 thanks for taking the time with all this 😸

**Comment by FloydianSound** [comment] 2024-02-29 04:52
Alright, so i was able to create a docker-compose file through the UI, and have both container running. i am however not seeing change in discord, i might be missing something obvious. you mentionned mountain a share for DRPP to fetch files from KASM, but i have not figured what you mean and which folder would it be. here's some screenshots.

![image](https://github.com/phin05/discord-rich-presence-plex/assets/97499891/ccc0c439-1f74-429a-93d2-03a621431247)
![image](https://github.com/phin05/discord-rich-presence-plex/assets/97499891/cb949a0c-d86c-48e0-87b9-15c06a64d05a)
![image](https://github.com/phin05/discord-rich-presence-plex/assets/97499891/c1a05ad7-6007-4e6c-924a-464a15f392b4)

here is my hierarchy
![image](https://github.com/phin05/discord-rich-presence-plex/assets/97499891/e0d8f92c-0a47-4429-b3e3-3af8c63187e8)
DRPP has only a config.yaml file inside, Kasmcord has 4 folders and a ICEauthority file.

and the YAML from the README (i had to make folders manually, otherwise it makes an error when trying to launch containers)
```
services:
  kasmcord:
    container_name: kasmcord
    image: kasmweb/discord:1.14.0
    restart: unless-stopped
    ports:
      - 6901:6901
    shm_size: 512m
    environment:
      VNC_PW: password
      XDG_RUNTIME_DIR: /run/user/1000
    volumes:
      - ./kasmcord:/run/user/1000
    user: "0"
    entrypoint: sh -c "chmod 700 /run/user/1000 && chown -R kasm-user:kasm-user /run/user/1000 && su kasm-user -c '/dockerstartup/kasm_default_profile.sh /dockerstartup/vnc_startup.sh /dockerstartup/kasm_startup.sh'"
  drpp:
    container_name: drpp
    image: ghcr.io/phin05/discord-rich-presence-plex:latest
    restart: unless-stopped
    volumes:
      - ./drpp:/app/data
      - ./kasmcord:/run/app:ro
    depends_on:
      - kasmcord
```

**Comment by phin05** [comment] 2024-02-29 05:00
1. Have you signed into Discord on the Kasm container?
2. Check the logs of the DRPP container. What do you see?

> you mentionned mounting a share for DRPP to fetch files from KASM, but i have not figured what you mean and which folder would it be

That's already done in the Compose file. The `kasmcord` folder is mounted into both the containers at the appropriate places.

> i had to make folders manually, otherwise it throws an error when trying to launch containers

Docker is supposed to create the folders automatically so I'm not sure why that is.

**Comment by FloydianSound** [comment] 2024-02-29 05:20
> 1. Have you signed into Discord on the Kasm container?
yes ! that worked like a charm.
> 2. Check the logs of the DRPP container. What do you see?
it mentionned logging into plex in a browser, which i did, then restarted the container. it asks me again.

i suspect a permission issue as usual. IIRC docker has a UID of 1000 and GID of 1000 ?
> 
> > you mentionned mounting a share for DRPP to fetch files from KASM, but i have not figured what you mean and which folder would it be
> 
> That's already done through the Compose file. The `kasmcord` folder is mounted into both the containers at the appropriate places.
> 
> > i had to make folders manually, otherwise it throws an error when trying to launch containers
> 
> Docker is supposed to create the folders automatically so I'm not sure why that is.
it seems to happen with every docker-compose.yaml file i create through the UI. doesn't create folders by itself, but it does fetch the image...

**Comment by FloydianSound** [comment] 2024-02-29 05:22
here is a screenshot of the error
![image](https://github.com/phin05/discord-rich-presence-plex/assets/97499891/79accc29-5ad1-4a66-aa80-59fc85a4c281)

**Comment by phin05** [comment] 2024-02-29 05:26
> it mentionned logging into plex in a browser, which i did, then restarted the container. it asks me again.

Are you sure your sign-in was successful? You should see a "Authentication successful" message in the DRPP container logs. I only see a "Authentication timed out" message in the screenshot.

> i suspect a permission issue as usual. IIRC docker has a UID of 1000 and GID of 1000 ?

There should be no permission issues since the proper permissions are set by the entrypoint in the Compose file and DRPP will adjust accordingly.

**Comment by FloydianSound** [comment] 2024-02-29 05:28
here is an updated SS

![image](https://github.com/phin05/discord-rich-presence-plex/assets/97499891/0d1ac647-5531-4192-ba5f-d41734283188)

**Comment by phin05** [comment] 2024-02-29 05:31
You missed [this](https://github.com/phin05/discord-rich-presence-plex?tab=readme-ov-file#other-info), so the Plex server name is set to `ServerName` by default. Edit the config.yaml file and change it to your Plex server's name.

**Comment by FloydianSound** [comment] 2024-02-29 05:41
> You missed [this (other info / env var section in README)](https://github.com/phin05/discord-rich-presence-plex?tab=readme-ov-file#other-info), so the Plex server name is set to `ServerName` by default. Edit the config.yaml file and change `ServerName` to your Plex server's name.

right... worst is i have read that part.
Container Manager UI doesn't allow you to setup ENV in advance other than inside the compose.yaml ... you would have to edit the container directly to add this variable, which needs to be built using the container manager. a real catch-22 ?

tried renaming the server to my server name, but everytime i save the file, it reverts back.

**Comment by phin05** [comment] 2024-02-29 05:51
I edited your comment to redact your Plex token which was exposed in your screenshot.

> Container Manager UI doesn't allow you to setup ENV in advance other than inside the compose.yaml

Setting it in the Compose file is the way, that's how it's done for all Docker containers while using Docker Compose. You don't need to edit the container or its image or the host environment variables.

Since you've already signed in now, you don't need to set it since it doesn't matter (unless you delete the config file). You just need to edit the config file to change `ServerName`.

> tried renaming the server to my server name, but everytime i save the file, it reverts back

I'm not sure what's going on there. It must be some issue with the container manager?

**Comment by FloydianSound** [comment] 2024-02-29 05:52
alright, to fix this broken thing....

i added the environment variables to the container as such: (last line)
![image](https://github.com/phin05/discord-rich-presence-plex/assets/97499891/2eaa56a0-67b6-4412-9b5e-cc74d022dafb)

then i have reset the container using the top right menu.

i deleted the local file config.yaml inside the DRPP folder

relaunched the whole project+containers

logged into plex web

logged into https://my.local.ip.address:6901 and into discord itself.

no errors

![image](https://github.com/phin05/discord-rich-presence-plex/assets/97499891/57f7fbbd-9fee-4818-82d5-cd0a9c7394f3)

and now it works !

![image](https://github.com/phin05/discord-rich-presence-plex/assets/97499891/9094e0ce-9e74-433b-9c88-6bbfc2c158db)

**Comment by FloydianSound** [comment] 2024-02-29 05:55
@phin05 thanks a lot for your assistance. i know it's outside "your" project, but i really appreciate your help and you accomodating us in this !

i can now be anywhere in the world and this will work without a PC on, ever !
i hope this whole thread will be useful for the next crazy people who wants to do the same.
i can also now uninstall that agent on windows that did great, but was the last thing i wanted to get rid and have things 100% hosted on the NAS itself.

**Comment by FloydianSound** [comment] 2024-02-29 06:03
as an added thing, you mentionned heavy overhead for kasmcord, and it might prove useful for others

there is a feature inside container manager to set resources limits. i set that to low and 4096 as shown here seems to have reduced the media usage from 60% to 30%
![image](https://github.com/phin05/discord-rich-presence-plex/assets/97499891/dfeae045-25e7-4d30-b8a3-8e9ed338b719)

you can see a comparison between the spikes (turned it on and off twice....)
![image](https://github.com/phin05/discord-rich-presence-plex/assets/97499891/9074fa94-94d7-48c7-aa5d-65d71cfc0a08)

**Comment by phin05** [comment] 2024-02-29 06:26
No problem, glad it works!

Also, I suggest revoking the exposed Plex token by deleting the PlexAPI device from https://app.plex.tv/desktop/#!/settings/devices/all since the screenshot containing the token is still cached on GitHub servers. You would have to clear the users list in the config (edit to `users: []`, or delete the file if you're still unable to edit it) and restart the container to make it prompt for authentication again.

**Comment by FloydianSound** [comment] 2024-02-29 06:34
i'm assuming you mean the DRPP one ?

![image](https://github.com/phin05/discord-rich-presence-plex/assets/97499891/324410c9-09f6-4f1b-9229-976802415486)

**Comment by phin05** [comment] 2024-02-29 06:41
Yeah that's the one, "PlexAPI" on the 3rd line.

**Comment by FloydianSound** [comment] 2024-02-29 06:50
done, done and done !

the file was still not editable, suspecting permissions as usual. deleting it did the trick.

works fine now, thanks for reminding me 😸

**Comment by FloydianSound** [comment] 2024-02-29 07:20
alright, interesting....

it worked fine for a while, then it simply stopped showing all of a sudden. then showed again for a couple of seconds, then off again.

no biggie, i restart the whole project.
then tried swapping to another song, showed for a few seconds, stopped again. i do notice there is a 30 second "delta" between my song counter and the display in discord. maybe something is up ?

here's a screenshot of the log, i can provide an HTML file if you need to read more
![image](https://github.com/phin05/discord-rich-presence-plex/assets/97499891/24e00279-5266-41ac-bbe6-b0a210ff1520)

![image](https://github.com/phin05/discord-rich-presence-plex/assets/97499891/73186c75-0ad6-456f-90e0-2c84c705e79d)

**Comment by phin05** [comment] 2024-02-29 07:38
Is this happening consistently? It appears to be a connection issue. The script tried to fetch an item from the Plex server, but the Plex server dropped the connection before this fetch request was completed.

**Comment by phin05** [comment] 2024-02-29 09:38
> then if i leave the preview going, it drops for a few seconds, then come back again, yet with a minute late timestamp

Are there any errors in logs when this happens? And does the timestamp correct itself after a few seconds? Discord doesn't update the rich presence immediately sometimes, and the script delays it a bit as well if the media being played hasn't changed, to prevent spamming requests to Discord.

> do note i use PlexAMP for this currently, but since it's all server side, it shouldn't really be an issue ?

Yeah, that should be fine.

**Comment by FloydianSound** [comment] 2024-02-29 09:56
i'll observe for a day or two and get back to you. thanks a lot for your help

**Comment by FloydianSound** [comment] 2024-03-01 02:42
i'm back !
so it does work intermitently. in the meantime i turned off the resources limitations to see if the syncing would improve.

still not quite there, tho the counter does seem to work fine when it "picks up" and it gets late when it "drops" and "picks up" again. pausing or pressing next/previous don't really seem like they send a trigger either ? (i might be wrong, trying to see how i can properly replicate the issue...)

here's a screenshots of the latest in the logs
![image](https://github.com/phin05/discord-rich-presence-plex/assets/97499891/55198b47-fe58-4c16-b2f9-59ee995bacb5)
![image](https://github.com/phin05/discord-rich-presence-plex/assets/97499891/2fbd808a-60ab-4cf0-8a5b-a300666ebb69)

let me know what you think, and where i can send a full log to you that won't leak any secrets !

**Comment by phin05** [comment] 2024-03-01 06:04
> it gets late when it "drops" and "picks up" again

Whatever timestamp is reported by Plex is sent to Discord without any modifications so I don't have control over this. Discord delays rich presence updates sometimes. You should see the new timestamp after a few seconds, when Discord decides to update the rich presence with the latest values.

> pausing or pressing next/previous don't really seem like they send a trigger either

Everything is still working for me on the latest version. You should be seeing activity in the logs and rich presence updates when you do that, as long as your connection to the Plex server is intact.

> here's a screenshots of the latest in the logs

The error here relates to the connection to your Plex server, same as the screenshot from yesterday. Unfortunately, this is not something that I can fix in the script. You'll have to investigate your network/connectivity by yourself.

**Comment by FloydianSound** [comment] 2024-03-02 20:56
thanks Phin, always appreciated.
FWIW ~ my plex server runs on the native os (not in a container) since it was a third party authorized package. i have updated it to 1.40 manually to keep things fresh. didn't notice a difference there.

everything else runs in their own containers. (that includes p2p, discord, DRPP, etc...), most of them have their own compose.yaml projects files as well.

you mentionned earlier there was a timeout happening maybe ? could it be that longer songs (dj sets) do not update their status in a short enough time that either DRPP or kasmcord thinks it's done ?!)

as for internal connection, i use both synology DSM (NAS) and Synology SRM (router), everything is wired with gigabit, i have a hard time seeing what could be the reason why connection drops (or packets loss). the only thing that is unusual with this setup is the bonded connection (eth0 and eth1 are the same -> Bond1) to allow higher bandwith (2x 1gb/s) and some kind of redundancy.

everything else works fine, so far. i wouldn't say it's a BIG dealbreaker, but if i can find the source and resolve it, it would make the experience better for sure (and probably help future people in this thread). i had thought maybe letting things settle a day or two would fix things once it all stabilized and i was less "on the case"

so i have left plexamp off for a day, didn't pay too much attention to my status updates. 
this morning i tried playing a song and it was picked up instantly... at this point i'm a bit confused at what could be the issue (i had thought maybe the performance is starting to be an issue, but everytime i look at the system performance, it barely gets that high. only if i do encodes/decodes or mess around big containers.)

could it be the VNC/KasmCord combo that gets throttled maybe ? can't seem to see CPU usage over the 30% mark for those containers, and maybe like 50-60% overall for the whole system as you said, it's a big overhead for a novelty, but i don't expect anyone to try and make an ultra-thin client for purely API purpose... not sure what to make of all this :)

**Comment by phin05** [comment] 2024-03-03 03:05
Sounds like your setup is solid so I'm not sure what's going on.

> you mentionned earlier there was a timeout happening maybe ? could it be that longer songs (dj sets) do not update their status in a short enough time that either DRPP or kasmcord thinks it's done ?!)

Discord will never assume that it's done, but DRPP will on a timeout. If you see "No recent updates from session key" in the logs, it indicates a timeout. That appeared in the last set of screenshots you sent, but it was caused because of the connection issue resulting in DRPP not having processed the previous update. Let me know if you see this message without any other errors in the logs around it.

> could it be the VNC/KasmCord combo that gets throttled maybe ?

The connection issue as per your screenshots is between DRPP and the Plex server, so Kasm couldn't have had anything to do with it.

**Comment by FloydianSound** [comment] 2024-03-07 08:31
been leaving it alone for a few days,
here is the problematic log entry.

![image](https://github.com/phin05/discord-rich-presence-plex/assets/97499891/5aa9f854-8f93-4024-80a9-eee5ac39df56)

so i assume from what you tell me, somewhere in there.... plex terminates that connection ?
is there some options in my plex server that could creat conflicts ?

**Comment by FloydianSound** [comment] 2024-03-07 08:43
all i can think of, is this setting. i have put it back to 0 for the moment, see how that goes :)
![image](https://github.com/phin05/discord-rich-presence-plex/assets/97499891/f2a4a658-4d7d-4a0d-a950-e4b28b44614d)
